apiVersion: v1
kind: Pod
metadata:
  name: javawebapp
  labels:
    app: java
  namespace: test-ns
spec:
  containers:
  - name: javawebappcontainer
    image: dockerhandson/java-web-application:1
    ports:
    - containerPort: 8080


