apiVersion: v1
kind: Pod
metadata:
  name: mavenpod
  namespace: test-ns
  labels:
    app: maven
spec:
  containers:
  - name: mavencontainer
    image: dockerhandson/maven-web-application:1
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mavensvc
  namespace: test-ns
spec:
  type: ClusterIP
  selector:
    app: maven
  ports:
  - port: 80
    targetPort: 8080
