apiVersion: v1
kind: Pod
metadata:
  name: java-nginx
  namespace: test-ns
  labels:
    app: javanginx
spec:
  containers:
  - name: javacontainer
    image: dockerhandson/java-web-application:2
    ports:
    - containerPort: 8080
  - name: nginxcontainer
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: javanginxsvc
  namespace: test-ns
spec:
  type: NodePort
  selector:
    app: javanginx
  ports:
  - port: 80
    targetPort: 80
    name: nginx
  - port: 8080
    targetPort: 8080
    name: tomcat
